"""Made the present_address NOT NULL

Revision ID: 2d70cb796108
Revises: b3ca56bf9caf
Create Date: 2025-10-24 03:48:38.691325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d70cb796108'
down_revision: Union[str, Sequence[str], None] = 'b3ca56bf9caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_contact_number_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_contact_number_key'), 'users', ['contact_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
