"""added attend_event and decline_event

Revision ID: 3e0e3e441f3e
Revises: da94de4b271c
Create Date: 2025-10-27 20:03:12.314782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0e3e441f3e'
down_revision: Union[str, Sequence[str], None] = 'da94de4b271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'attend_event';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'decline_event';")
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
