"""change sex to non-nullable

Revision ID: 4dfb5481690c
Revises: f9d85800e127
Create Date: 2025-09-16 19:42:53.442332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dfb5481690c'
down_revision: Union[str, Sequence[str], None] = 'f9d85800e127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='sexenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='sexenum'),
               nullable=True)
    # ### end Alembic commands ###
