"""add start_time_startday, end_time_startday, start_time_endday, and end_time_endday  to events

Revision ID: 5e2c502bbcb7
Revises: c419c0f0f717
Create Date: 2025-11-02 23:30:55.124327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e2c502bbcb7'
down_revision: Union[str, Sequence[str], None] = 'c419c0f0f717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time_startday', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time_startday', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('start_time_endday', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time_endday', sa.Time(), nullable=True))
    op.drop_constraint(op.f('events_approved_by_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'remarks')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'approved_by')
    op.drop_column('events', 'status')
    op.drop_column('events', 'approved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_approved_by_fkey'), 'events', 'users', ['approved_by'], ['id'])
    op.drop_column('events', 'end_time_endday')
    op.drop_column('events', 'start_time_endday')
    op.drop_column('events', 'end_time_startday')
    op.drop_column('events', 'start_time_startday')
    # ### end Alembic commands ###
