"""addd is_read to activity_logs

Revision ID: 7c05d69ab453
Revises: 3e0e3e441f3e
Create Date: 2025-10-28 15:01:35.678423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c05d69ab453'
down_revision: Union[str, Sequence[str], None] = '3e0e3e441f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'is_read')
    # ### end Alembic commands ###
