"""added columns for QR code

Revision ID: ac1e1f3e9ea5
Revises: 7c05d69ab453
Create Date: 2025-10-28 22:23:15.726307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1e1f3e9ea5'
down_revision: Union[str, Sequence[str], None] = '7c05d69ab453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendance', sa.Column('qr_token', sa.String(), nullable=True))
    op.add_column('event_attendance', sa.Column('is_valid', sa.Boolean(), nullable=True))
    op.add_column('event_attendance', sa.Column('scanned_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'event_attendance', ['qr_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_attendance', type_='unique')
    op.drop_column('event_attendance', 'scanned_at')
    op.drop_column('event_attendance', 'is_valid')
    op.drop_column('event_attendance', 'qr_token')
    # ### end Alembic commands ###
