"""Add present_address to gts_responses

Revision ID: b3ca56bf9caf
Revises: ec2426f80468
Create Date: 2025-10-24 01:21:23.535788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ca56bf9caf'
down_revision: Union[str, Sequence[str], None] = 'ec2426f80468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gts_responses', sa.Column('present_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gts_responses', 'present_address')
    # ### end Alembic commands ###
