"""add start_time and end_time to events

Revision ID: c419c0f0f717
Revises: e733f953c7ea
Create Date: 2025-11-02 21:49:44.481602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c419c0f0f717'
down_revision: Union[str, Sequence[str], None] = 'e733f953c7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
