"""Make present and permanent address null

Revision ID: ca3c4e4d9308
Revises: 5d447a3ec761
Create Date: 2025-10-24 04:14:24.575894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3c4e4d9308'
down_revision: Union[str, Sequence[str], None] = '5d447a3ec761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'present_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'permanent_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permanent_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'present_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
