"""removed event_date changed to start and end date

Revision ID: da94de4b271c
Revises: ca3c4e4d9308
Create Date: 2025-10-26 23:59:53.062587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da94de4b271c'
down_revision: Union[str, Sequence[str], None] = 'ca3c4e4d9308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('end_date', sa.Date(), nullable=False))
    op.drop_column('events', 'event_date')
    op.alter_column('gts_responses', 'present_address',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gts_responses', 'present_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('events', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###
