"""Make civil_status nullable in gts_responses

Revision ID: f9d85800e127
Revises: 3f2f8c25c7fe
Create Date: 2025-08-28 16:43:29.985536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d85800e127'
down_revision: Union[str, Sequence[str], None] = '3f2f8c25c7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gts_responses', 'civil_status',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gts_responses', 'civil_status',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
