"""Add non_employed_reasons column to gts_responses

Revision ID: fc0a7c56335f
Revises: 4dfb5481690c
Create Date: 2025-09-16 21:59:04.332859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc0a7c56335f'
down_revision: Union[str, Sequence[str], None] = '4dfb5481690c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gts_responses', sa.Column('non_employed_reasons', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gts_responses', 'non_employed_reasons')
    # ### end Alembic commands ###
